### ISSUE TITLE
duplicate consumer registered

### ISSUE THREAD

**Issue by famagusta** [depop/celery-message-consumer#17]
Sometimes the celery worker is printing the following message 
"Received and deleted unknown message. Wrong destination?!?"
This happens on every alternate message.
On further investigation I could seeing a duplicate consumer in rabbitmq (list_consumers).
I use supervisor to run the workers. Any idea why this behaviour is happening?

**Comment by anentropic** [comment]
I've never seen that, I would guess some problem with supervisor or deployment

**Comment by famagusta** [comment]
yes. it looks like a celery issue. i tried with the celery consumer bootstep and got the same issue.

**Comment by famagusta** [comment]
It seems this happens when running celery with django. The celery worker starts an extra consumer listening for tasks routed to the queue with the same routing_key. This will cause every alternate message to be routed to the task consumer which does not recognize the message and discards it.
Proposed solution is add a custom command-line option to start a consumer just for custom messages.

Details can be found here https://github.com/celery/celery/issues/2979
